package finalproject.Ger_garage.Controllers;

import finalproject.Ger_garage.Models.*;
import finalproject.Ger_garage.Repositories.BookingRepository;
import finalproject.Ger_garage.Repositories.ItemRepository;
import finalproject.Ger_garage.Repositories.MechanicRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.*;

import finalproject.Ger_garage.Repositories.UserRepository;

import javax.validation.Valid;
import java.util.Optional;

@Controller
@RequestMapping("admin")
public class AdminController {

	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	@Autowired
	private BookingRepository bookingRepository;
	@Autowired
	private MechanicRepository mechanicRepository;
	@Autowired
	private ItemRepository itemRepository;
	/**
	 * Display all registered users
	 * @param model
	 * @return
	 */
	@GetMapping("users")
	public String  allUsers(Model model) {
		//model.addAttribute("name", "users");
		model.addAttribute("allUsers", userRepository.findAll());
		return "admin/users";
	}

	/**processed with "form"
	 * delete a user by id
	 * @param id
	 * @return
	 */
	@PostMapping("users")
	public String deleteUser(@RequestParam Integer id) {
		userRepository.deleteById(id);
		return "redirect:users";
	}


	/**
	 * Displays all bookings
	 * @param model
	 * @return
	 */
	@GetMapping("bookings")
	public String  allBookings(Model model) {
		model.addAttribute("bookings", bookingRepository.findAll());

		return "admin/bookings";
	}

	/**
	 * Display specific booking
	 * View can not render Optional format, we have to pars only Object
	 * @param id
	 * @param model
	 * @return
	 */
	@GetMapping("booking-details/{id}")
	public String  oneBooking(@PathVariable Integer id, Model model) {
		bookingRepository.findById(id).ifPresent(o -> model.addAttribute("booking", o));

		model.addAttribute("mechanics", mechanicRepository.findAll());
		model.addAttribute("items", itemRepository.findAll());

		return "admin/booking-details";
	}

	/**
	 * Updates booking by changing booking status, mechanic, and price
	 * @param booking
	 * @param errors
	 * @param model
	 * @return
	 */
	@PostMapping("update")
	public String updateBooking(@ModelAttribute("booking") @Valid Booking booking, Errors errors, Model model) {
		// We have to transfer items from old booking since thymeleaf form doesn't submit them
		Booking oldBooking = bookingRepository.findById(booking.getId()).get();
		Booking newBooking = booking;
		newBooking.setItems(oldBooking.getItems());

		bookingRepository.save(newBooking);
		return "redirect:bookings?updated";
	}

	/**
	 *  adding items to the booking with URL
	 * @param id
	 * @param itemId
	 * @return
	 */
	@GetMapping ("additem/{id}/{itemId}")
	public String addItems(@PathVariable Integer id, @PathVariable Integer itemId) {
		Booking booking = bookingRepository.findById(id).get();
        Item item = itemRepository.findById(itemId).get();
		booking.getItems().add(item);
		//alter the price every time new item added
		booking.setPrice( booking.getPrice() + item.getPrice());
		bookingRepository.save(booking);
		return "redirect:../../booking-details/{id}?added";
	}
	/**
	 * remove items to the booking with URL
	 * @param id
	 * @param itemId
	 * @return
	 */
	@GetMapping ("deleteitem/{id}/{itemId}")
	public String deleteItems(@PathVariable Integer id, @PathVariable Integer itemId) {
		Booking booking = bookingRepository.findById(id).get();
		Item item = itemRepository.findById(itemId).get();
		booking.getItems().remove(item);
		//alter the price every time new item added
		booking.setPrice( booking.getPrice() - item.getPrice());
		bookingRepository.save(booking);
		return "redirect:../../booking-details/{id}?deleted";
	}

//	/**
//	 * adding items to the booking with model
//	 * @param id
//	 * @param item
//	 * @return
//	 */
//	@PostMapping("additem/{id}")
//	public String addItems( @ModelAttribute ("item") @Valid Item item, Errors errors, @PathVariable Integer id) {
//		Booking booking = bookingRepository.findById(id).get();
//
//		booking.getItems().add(item);
//		booking.setPrice( booking.getPrice() + item.getPrice());
//		bookingRepository.save(booking);
//		return "redirect:../booking-details/{id}";
//	}
}
