package finalproject.Ger_garage.Controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import finalproject.Ger_garage.Repositories.UserRepository;

@Controller
@RequestMapping("admin")
public class AdminController {

	
	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	/**
	 * Display all registered users
	 * @param model
	 * @return
	 */
	@GetMapping("users")
	public String  allUsers(Model model) {
		//model.addAttribute("name", "users");
		model.addAttribute("allUsers", userRepository.findAll());
		return "admin/users";
	}
	

	
	/**processed with "form"
	 * delete a user by id
	 * @param id
	 * @return
	 */
	@PostMapping("users")
	public String deleteUser(@RequestParam Integer id) {
		userRepository.deleteById(id);
		
		return "redirect:users";
	}
}
